[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
spl_with_metadata = "J72XdorZyciQyrVHJvZfyhVzYWHfWPGRbtRtbor3RPst"
token_escrow = "BxaG13bDcy3YwQUfbJHYQQR6rAwt47acUuoSSWSMc1yt"
zk_escrow_sol = "7QoUPfkaSaMgq7wddq4sU78wEm6TnMHd3nxVGcMPDcAy"

[programs.localnet]
spl_with_metadata = "HxunzzbyMwMxfUc2vs6w9ty1LN97GvjU3NPuRPVrhSjM"
token_escrow = "BxaG13bDcy3YwQUfbJHYQQR6rAwt47acUuoSSWSMc1yt"
zk_escrow_sol = "7QoUPfkaSaMgq7wddq4sU78wEm6TnMHd3nxVGcMPDcAy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.test.ts\""
