[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_escrow_sol = "J47TtwjNm5VUNLn5XE5goTLKXBuQEpzE5gVPZ85W6EkU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.test.ts\""
