[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_escrow_sol = "A8oUCtSKbVxthxxLiWNWnRBjhZYpJen2zC2wHGWrSqYb"
token_escrow = "EsF9CU3PUf1nQZYFDaq9ws3b8YfbsC84s2MSDbSX8znw"
nullifier_registry = "Nu11ifier1111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.test.ts\""
